### ISSUE TITLE
训练显示矩阵乘法形状不兼容

### ISSUE THREAD

**Issue by 7csd** [QinHsiu/ICSRec#17]
测试可以跑出来结果，但是自己训练就是会报错，现实这个矩阵乘法形状不兼容。为什么

**Comment by 7csd** [comment]
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265; details: cublas failed (13): (512, 64) x (256, 64)' = (512, 256) gemm params m 256 n 512 k 64 trA T trB N lda 64 ldb 64 ldc 256

报错显示是这样的，我运行那篇ICLRec会出现一模一样的报错，为什么呢，卡我很久了

**Comment by QinHsiu** [comment]
你好，看报错信息可能是因为faiss版本问题导致的，你可以重新安装faiss版本试一试：
conda install -c pytorch faiss-gpu
在验证的时候没有报错是因为验证的时候不需要再使用faiss包，不需要重新进行意图聚类，所以是正常的；

**Comment by 7csd** [comment]
哦哦，好的，谢谢哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月22日(周六) 晚上11:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QinHsiu/ICSRec] 训练显示矩阵乘法形状不兼容 (Issue #17)


   
你好，看报错信息可能是因为faiss版本问题导致的，你可以重新安装faiss版本试一试：
 conda install -c pytorch faiss-gpu
 在验证的时候没有报错是因为验证的时候不需要再使用faiss包，不需要重新进行意图聚类，所以是正常的；

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  QinHsiu left a comment (QinHsiu/ICSRec#17)
 
你好，看报错信息可能是因为faiss版本问题导致的，你可以重新安装faiss版本试一试：
 conda install -c pytorch faiss-gpu
 在验证的时候没有报错是因为验证的时候不需要再使用faiss包，不需要重新进行意图聚类，所以是正常的；

**Comment by 7csd** [comment]
OK，感谢博主，这个问题我解决了，我跑出来了，请原谅我再麻烦你一次可以吗，就是他在构造子序列的时候，会给子序列一个目标物品，但是论文里没写目标物品怎么来的，我代码也没看见呢，可以帮我解答一下嘛，我真的好菜😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月24日(周一) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QinHsiu/ICSRec] 训练显示矩阵乘法形状不兼容 (Issue #17)




 
Closed #17 as completed.

**Comment by QinHsiu** [comment]
你好，你可以看一下 https://github.com/QinHsiu/ICSRec/blob/main/src/datasets.py 第18行代码，这个类主要是用来产生子序列的label的。
